### PR TITLE
Dhg train pred

### PR DESCRIPTION
**Pull request by DaniDelHoyo**
Added option for loading a pretrained model from a previous protocol in the project.
Added option of skipping training when a pretrained model is loaded.
Training model results are moved to extra folder so they are not deleted from tmp.

### CODE REVIEW

**Comment by DaniDelHoyo** [comment]
Would address https://github.com/scipion-em/scipion-em-topaz/issues/8

**Comment by pconesa** [comment]
In Cryolo, we followed a more generic approach:
1.- Protocol to import a model (outputs a topaz model)
2.- Protocol to train (outputs a model). Not sure if it can be fed with an existing model (imported)  to accumulate training?
3.- Prediction protocol

I think this PR allows for "inter project" training reusability. Option above, allow for inter project training. 

Now, I do not know if is worth that change. Any ideas?

**Comment by delarosatrevin** [comment]
I haven't seen at this PR changes, but I suggest that we should do the same
as in cryolo if possible

Cheers,
José Miguel

**Comment by pconesa** [comment]
@azazellochg , @DaniDelHoyo thought you were the maintainer of this plugin, thus you were the reviewer. You are very welcome to review it if you want, but you are excused by default. ;-)

**Comment by azazellochg** [comment]
Can someone remind me, why we have import protocol in cryolo if the model file is just a hdf file?

**Comment by pconesa** [comment]
Forgot this! Not a big difference though from using a "path" param.

Let say you have an external model you want to retrain regularly so:

1.- import (only here you specify the path)
2.- retrain
3.- pick

Otherwise: you'll have to specify the path in the training and in the picking.

Also, let say you have an existing model you don't want to train, then:
1.- import
2.- pick

In both cases, picking is fed with a model

Otherwise, picking should have a path param (for the second case) and a input param (training protocol) for the second case.

Also, for streaming cases, a protocol when scheduled is waiting until all input is ready. Path parameters are not taken into account so protocol will be launched even if the model is not there. Which force us to have the training as an input in the picking.

So I guess is "like", having a constant (model as output) and reusing it, or "copying" the same value again (entering the path twice in first case). Could be more if you try different picking parameters.

**Comment by DaniDelHoyo** [comment]
This commit has a functional and separated version of the training and picking protocols and their test.
I have maintained the "all in one" protocol version, but maybe it is just better deleting it, it is the file making the conflict.

**Comment by azazellochg** [comment]
Thanks, @pconesa . I was thinking of having 
1) path param for training protocol, output is a trained model which is a scipion object
2) picking protocol where you can choose input model from a file or from training output

If you have "an external model you want to retrain regularly" then I presume you are doing different projects and will have to run import protocol anyway.

But I'm fine with the current setup in cryolo plugin

**Review by pconesa — APPROVED** [review]
Looks ok, tests are passing and manual usage has worked. Good job.

**Pull request merged**
